language: objective-c
osx_image: xcode14.2 # Choose the appropriate Xcode version

before_install:
  - bundle lock --add-platform x86_64-darwin-21
  - chmod +x downloadFrameworks.sh
  - ./downloadFrameworks.sh

script:
  - xcodebuild -resolvePackageDependencies -scheme Code\ UI -project ./Code.xcodeproj
