language: objective-c
osx_image: xcode14.2 # Choose the appropriate Xcode version

before_install:
  - bundle lock --add-platform x86_64-darwin-21
  - chmod +x downloadFrameworks.sh
  - ./downloadFrameworks.sh

script:
  - xcodebuild -resolvePackageDependencies -scheme Code\ UI -project ./Code.xcodeproj 
  - xcodebuild -scheme Code\ UI -project ./Code.xcodeproj -destination 'platform=iOS Simulator,id=1FBBD280-B85C-4F94-97BF-60B47BFBA2B5,OS=16.2,name=iPad mini (6th generation)' build
  
deploy:
  provider: s3
  access_key_id: R2_ACCESS_KEY_ID
  secret_access_key: R2_SECRET_ACCESS_KEY
  bucket: "static"
  endpoint: R2_ENDPOINT
  glob: "Code.ipa"

env:
  global:
  - secure: YKgTNia2z9b7yxvuaIMtaySMB5/kXnPvVxmjqdkFgs8YrkZpc7RGkK61jKH7jgKe2tC1c9lsAoMaKKuBqPL7t2FhASBNU15WdQyeGpW8MgQoZZOW+8dxN4aXuQCOqaXV6xa0pDIJzpJTFsUXQ83avqcOMWVoiV4tRYF2PkVcS0Bxxi6nYUtv0NWnT118TTzUpMo/6f+VE6Hwj+47j2bfjZMS+1N8safZM2keo5yaQPZZx4CEN0G4x5R5JfALv8Z/YPmH/QF00otJ/golqtdGXDUttFsVC/BN4nPQTGQLK8z5rh2nqDZ3smXeD190b9AM3n9700GeKiSJZzFZM4b2Q5yO9GuK2N94QzpPK/YKRDHPUo/2a20PZbUxeIA29wxdpYWPcuLC6Fh9SikL0os7Itw6g7nyXiF0Hw9c8983SBZyk/+C0gKOrxjC/GsuDvDHjRvVNtZBYQBLzKb2jKumHt/RUix8ghUa+9IbDvJ9+mfqGDOXRSy3KMrK5agTQyN6XRK1OhafDscULdY97rIFi984dbnTwA3aLhdzHeAv04E4tpR8iiQ9DcLGwKVZVzqGPSBKfpKQE0pyadlur56tLwkLp4ATgRg0tMZfMH7QsFaYrVSbuomBUJiV3qciqUNLf+UxEwi2ABZtAeE/E+0NmEiIO7uofKOo0bz/b94CYe0=
  - secure: k8NgBg58+VmBi7HBZaSl5tHPEIfuWIKzhBtIzzOSqHX+NanmE44oEKuId+ZbMt2ruwlkZ2zcAaF355dwcKhxzY3mnJZm3PihGP1EZ0q+E9pgNXk1J5mDu7W1wXaoAE2Zv+WIThQwq2KQemwJm9YEtLcZcxM7RIHXrM6eM3LKsaT5k4FjiPj8oRCKn3S2arTaK2V6WJYhDiOT8N649l7uHuXbRlXbGLLnFOS0c4ZgjNzFlYsLd8qa1UVOmVKxL6zk2iQIuIQBkS9/Iy03xU4QFmatgl6YYDlfiJjFz7w6U0IG6mFwz8gBJhogPVQ3hY2yw5eD1OWq0XmOsAD3DyfbcAczKhu6ay35cuHTObPT6dpfLMQ4bPCYlcpj60d3vtJHOFe3U4VMns1WYr5ls1M98gh5eWDDBXUVqhcrMtGKUGn7II00DJ4zXz0MCpSgAlHsTq6UendFjqFbt/KeoycitHaPWSSK5lJA8/avTyszCnR2DZIvdbT7ZS4tAwOoBo22YoJv8BmZQRrC9BuUtdykP+PkKNfwgABRKz4cXKRZAhfdub0idN12JdXUaIcb7tcmP5+JOS4dbP6KZOnxTd7TlvZpA0trxee+vN7KllolsG6X3Pw7ESV3PIll/7kKYrdJfcxHBRg02Iu1qjXntmT/jRPUc9RKLwKQ3ZaKhv7WMWA=
  - secure: CwcQ90yhO6TekBPZqrS0oJgpxEsSiPpAuN7XukVpgmCE2OONEOoPy6MLJcY2EIsoGQCkwk4zVimHe5nMzq+9lnsGmkUFkQHNncYpJLh7ut3/6osnHQNHJEYkcmKM4CHq5+HCL3ZZZzGYaqQQ398q72cr8UJx016sS0k+NyNDMgBBZxC958to92pHlIzBP+I24dIJFCLy7oEiVlyqgCNXG4EahNhilnznOUOQyZ2yEhKtM3Q0QncyNCYYOBX1dkEE8NDn4Imtn3lEx70HacyHI+6iXoJLc3DhWA8qmr3fIG/HsY5bIwxlZR4gLAzylK/bPYt6qZDVLIVlLM5Iy7zJI+9b7UCyDqmOlsr2TUBUB6ehMPaD2aYSmqB5lCd4OExhqDlQE5l7fwrcq3tR9I7lOdfH7yTCrsVgK/CC3kyoRQWW4vptalke6to28ot1IGpCreRBujnLFkfR+ShgXDuXadAzd9PshVf1+ItDfk2KeseuBWaUa3YGFYRsdUHjLocNgE/mwNle9t32vKFx+HlvzRF4D8+2CmZ7RHP1LrUGk8TvF9dRYNlxvc516INGczPI+hj56INFKE4ZgWT54xOb80Gspd4aDR9LX7ABDHhquZDty6vqSRRcR5LdfTQx+wZzJdcWxoBnfzCbzlAyDZoKw+EWSebKmInLdeHfaMIsrQ4=
