language: objective-c
osx_image: xcode14.2 # Choose the appropriate Xcode version

before_install:
  - bundle lock --add-platform x86_64-darwin-21
  - chmod +x downloadFrameworks.sh
  - ./downloadFrameworks.sh

script:
  - xcodebuild -resolvePackageDependencies -scheme Code\ UI -project ./Code.xcodeproj 
  - xcodebuild -scheme Code\ UI -project ./Code.xcodeproj -destination 'platform=iOS Simulator,OS=16.2,name=iPad mini (6th generation)' build | xcpretty
  
deploy:
  secret_access_key:
    secure: D1T0nUAx3vVxo7boaHfXYKbdAw8YZply1C3VynBis3peob9Krtl1j7wPSQ4RxNycqKBw/MtL9ZEzTHJTHPiqNCdO/UA/taquYP2KP4ONr0WlQ4hJCd8feafAj78myeDZE5FdMGLyFECm5JfHk6m/QqgGYA/aJpySWJXTtMiJTnD995wwIoUCYaZsk0sKK5bCcjcwPbL0gjwKmI86jSfdC7vHquOeukSgtips3YgwbgRSdOwbXbDn8mJ/Pmbib8jsklKDlQJO/NlXjeTPEOLONOkQJKbk49pkBgUKs7S1fnJ4TOwU0kmX/1cjcUtcU+0rjBukHJzZ5ofj/ds5O+2ANvA4A3y27H9FXKhsldpqZ1W4ldLIpnGnnps0N/VjU3CcrAysMivKUcpktI2Kuleund5Kj3GapmlZQYYYTTEuYpmPE+oj1HkZ/I2gzNuIsClrXrLlCCmn30XGGO0HEjLpI0qnBukT8CpPVCgeZdLjynEb6o+aFo3BiL5BYC+lfccGBecLMtlL6jW1hDrd61KbpkwfJOLluvSUS1ZEBVnux3jQ79rCK7qjxPyHvGQFVL/8g4Br6pT1ObLbDgRwYcUR7V18avCzkd6t6a/v/Ym9QEVokzYAv/QT+kPCehMfqxwN74zuU3X+jtCIgLIe+iswPYZvQMEFmBk9M3Sao4TB/to=
  access_key_id:
    secure: iA3fZdLHCrhIAADzG8HhdyMnkIPaXCUt1ge4KrGnDv8u4PpbRfTqq7RUju66Ji4X1Al7I/pawd0GVU8rOjQIKJO1zwybZTkKBP+LfkD+ECpkNDD0EyWUmKqQBpO8/p6J9ZdEu2np5cAo5mg3j7fgpX75dK9Fe+NYh1pj8yvktFkZBTH+tJzAEbmrtGesWqhaunL/ebswS6khkq3Wqnlrt+V9aQFMt7iWLM4iK0mq4e1b+mqQlh4jA9Bu6ctFcfEd/v85usNvfZNodBZgZ/jeyUpYbK+pBEw+/FkbSn7F7RITVlXTGQI8zZW6VGe9e/o7UBu/b+L8VNKS7gB+Tot84Y2im7KMquzrkzH1adJ6vC+M7UrmYUW+qaPar6DF8MK3NwZWmwwXhUn0ualyoGx4JyI3QeZb/JVwEAwdSsgpFIzIVYYi1lnvSZu/kQl2GpwPLyP78Xyrng3Z8SxQ57/XSMaZJxV6F6xZL4jcrXtzoNTTviZIlw5FnBBTulcYRAS2xjirBIYwP4eNmhzstcCsaHgBHz04C7PxrtICBHAoJgBtxUwnygWumSpKp1yju//3WKKfFakLeelQ/Je22wTgEb8WidBX+2nWqd7FqewYBYv/kTuwkTA92Le4BkXiJzmmOnljZv25gU8vzblYvKjhLGQ1pmsjDrlv8Bf1c4sIBfY=
  endpoint:
    secure: plJDDvc/2rajZOi/MuTM9MJvQ9mK09CuQVhJUXUKFvXMrkcwAFVRxVDAxRSLyOoBzPJgjSyU/+5Hy5AY5JQwAhLYorwtPPB92RtlPcXqlgFc3SXqLY6Xt0DOY7N48U7WoIS/NQVwe/kMy78VIvNv5FQw+cr/v56l8hytZufS8cb6+i2USsXdYA0FwIX4iPwzPvRFOLugSZyoIxwSZ2YLgUDXMQqo8AEdubmWawSGBa4hbT6OOmZs4DAD6Qqhg15r7z2zcbiVN7OMOHGcBeW/3GnCUH/rIf2kndWghiNLrl53uSgXYu4hErDAqcJgwmhSoV6iGXUDYpocq3QpQydHGXSApSn+XsM1n7kRqogqg0zA7Sn59dVZyThIfxdRUzI3haFM0ACDfuDxVIfy6zNERoaH2RRvPcoOBDzDVNqdNxuTt1l1i+uuPgsDCvqgTkVyQ4ij5KSkzaoCM7rQt5YjcjcZNrtPKSy53ossRH2b73yofT0JlNUmbWK1TtnWjbivBBoPQyYOlAkpJmiHn2IQh+e/siIe0G7p6IH3jKbJe5Hn2WKt79SZ1EQkioao/MMsTipyn3sryFWBfbsarfVQF6F25q1ANxGYbq1d88pE96Azy/GielSMHdRdyE9F1K0Z6XyszvsPCW7/SjF3WcLqL+wXLPUOycV342qXNyYCHAI=
  provider: s3
  bucket: "static"
  glob: "Code.ipa"
  on:
    branch: main
