default_platform(:ios)

lane :build_unsigned_ipa do
  gym(
    scheme: "Code App",
    export_method: "ad-hoc",
    project: "Code.xcodeproj",
    destination: "platform=iOS Simulator,OS=16.2,name=iPad mini (6th generation)",
    clean: true,
    output_name: "Code"
  )
end
